### ISSUE TITLE
warning CS1591 in compilation

### ISSUE THREAD

**Issue by kalpasrl** [KafkaWannaFly/BindableProps#44]
HI, congratulations for a great job.

I have a request, in our projects we use API documentation generation and using the library hundreds of warnings are produced in the generated code.

**Example:**
warning CS1591: Missing XML comment for publicly visible type or member 'BannerView.TitleProperty'

I know it's possible to handle this, but it has to be done within the library.

Thank you
Stefano

**Comment by KafkaWannaFly** [comment]
Hi @kalpasrl 
Please try to install the latest version. Hope this will fix 😃

**Comment by kalpasrl** [comment]
Thank you very much @KafkaWannaFly
